# Generated by Django 4.2.29 on 2026-04-08 04:31

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('source', models.CharField(default='huggingface', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, help_text='Path relative to MEDIA_ROOT where the original file is stored.', max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('file_mime', models.CharField(blank=True, max_length=100)),
                ('markdown_text', models.TextField(blank=True, help_text='Markdown extracted by Docling from the original file.')),
                ('search_text', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
