# Generated by Django 4.2.29 on 2026-04-13 02:24

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('contributor', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='uploads/')),
                ('file_mime', models.CharField(blank=True, max_length=100)),
                ('markdown_text', models.TextField(blank=True)),
                ('search_text', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
