# Generated by Django 4.2.29 on 2026-04-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_size',
        ),
    ]
